### ISSUE TITLE
PsExec not found

### ISSUE THREAD

**Issue by rsvincef1** [rebrec/hurry#8]
**Describe the bug**
It seems to be a path problem, the psexec executable is not found when it is under "c:\windows\system32". When we copy the executable under "c:\windows", it works.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 build xxxx / Debian Stretch]

**Additional context**

**Comment by rebrec** [comment]
Please fill the issue template
